# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

inhibit_all_warnings!

target 'SocketProject' do

pod 'SocketRocket'
pod 'MBProgressHUD'
pod 'AFNetworking'

end

target 'SocketProjectTests' do

end

